// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transcendence.Data;

#nullable disable

namespace Transcendence.Service.Migrations
{
    [DbContext(typeof(TranscendenceContext))]
    [Migration("20250511063835_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.HistoricalRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .HasColumnType("text");

                    b.Property<string>("RankNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId");

                    b.ToTable("HistoricalRanks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Summoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .HasColumnType("text");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<long>("RevisionDate")
                        .HasColumnType("bigint");

                    b.Property<string>("RiotSummonerId")
                        .HasColumnType("text");

                    b.Property<long>("SummonerLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("SummonerName")
                        .HasColumnType("text");

                    b.Property<string>("TagLine")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Summoners");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("EndOfGameResult")
                        .HasColumnType("text");

                    b.Property<long>("MatchDate")
                        .HasColumnType("bigint");

                    b.Property<string>("MatchId")
                        .HasColumnType("text");

                    b.Property<string>("Patch")
                        .HasColumnType("text");

                    b.Property<string>("QueueType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<List<int>>("Items")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RunesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SummonerSpell1")
                        .HasColumnType("integer");

                    b.Property<int>("SummonerSpell2")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("RunesId");

                    b.HasIndex("SummonerId");

                    b.ToTable("MatchDetails");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchSummoner", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchId", "SummonerId");

                    b.HasIndex("SummonerId");

                    b.ToTable("MatchSummoners");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.Runes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Perk0")
                        .HasColumnType("integer");

                    b.Property<int>("Perk1")
                        .HasColumnType("integer");

                    b.Property<int>("Perk2")
                        .HasColumnType("integer");

                    b.Property<int>("Perk3")
                        .HasColumnType("integer");

                    b.Property<int>("Perk4")
                        .HasColumnType("integer");

                    b.Property<int>("Perk5")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryStyle")
                        .HasColumnType("integer");

                    b.Property<int[]>("RuneVars0")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int[]>("RuneVars1")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int[]>("RuneVars2")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int[]>("RuneVars3")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int[]>("RuneVars4")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int[]>("RuneVars5")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("StatDefense")
                        .HasColumnType("integer");

                    b.Property<int>("StatFlex")
                        .HasColumnType("integer");

                    b.Property<int>("StatOffense")
                        .HasColumnType("integer");

                    b.Property<int>("SubStyle")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Runes");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentChampionLoadout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CurrentChampionLoadouts");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentDataParameters", b =>
                {
                    b.Property<Guid>("CurrentDataParametersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Patch")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CurrentDataParametersId");

                    b.ToTable("CurrentDataParameters");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.Helpers.UnitWinPercent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CurrentChampionLoadoutId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfGames")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("WinRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CurrentChampionLoadoutId");

                    b.ToTable("UnitWinPercent");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.HistoricalRank", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany()
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Rank", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("Ranks")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchDetail", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany("MatchDetails")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Match.Runes", "Runes")
                        .WithMany()
                        .HasForeignKey("RunesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany()
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Runes");

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchSummoner", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany("MatchSummoners")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("MatchSummoners")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.Helpers.UnitWinPercent", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Service.CurrentChampionLoadout", null)
                        .WithMany("UnitWinPercents")
                        .HasForeignKey("CurrentChampionLoadoutId");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Summoner", b =>
                {
                    b.Navigation("MatchSummoners");

                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.Match", b =>
                {
                    b.Navigation("MatchDetails");

                    b.Navigation("MatchSummoners");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentChampionLoadout", b =>
                {
                    b.Navigation("UnitWinPercents");
                });
#pragma warning restore 612, 618
        }
    }
}
