// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transcendence.Data;

#nullable disable

namespace Transcendence.Service.Migrations
{
    [DbContext(typeof(TranscendenceContext))]
    [Migration("20251009194304_Non Null")]
    partial class NonNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatchSummoner", b =>
                {
                    b.Property<Guid>("MatchesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SummonersId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchesId", "SummonersId");

                    b.HasIndex("SummonersId");

                    b.ToTable("MatchSummoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.HistoricalRank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .HasColumnType("text");

                    b.Property<string>("RankNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId");

                    b.ToTable("HistoricalRanks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId", "QueueType")
                        .IsUnique();

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Summoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<string>("PlatformRegion")
                        .HasColumnType("text");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<long>("RevisionDate")
                        .HasColumnType("bigint");

                    b.Property<string>("RiotSummonerId")
                        .HasColumnType("text");

                    b.Property<long>("SummonerLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("SummonerName")
                        .HasColumnType("text");

                    b.Property<string>("TagLine")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Puuid");

                    b.ToTable("Summoners");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("EndOfGameResult")
                        .HasColumnType("text");

                    b.Property<long>("MatchDate")
                        .HasColumnType("bigint");

                    b.Property<string>("MatchId")
                        .HasColumnType("text");

                    b.Property<string>("Patch")
                        .HasColumnType("text");

                    b.Property<string>("QueueType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchDate");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("QueueType");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("ChampLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("NeutralMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .HasColumnType("text");

                    b.Property<Guid>("SummonerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SummonerSpell1Id")
                        .HasColumnType("integer");

                    b.Property<int>("SummonerSpell2Id")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamPosition")
                        .HasColumnType("text");

                    b.Property<int>("TotalDamageDealtToChampions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMinionsKilled")
                        .HasColumnType("integer");

                    b.Property<int>("VisionScore")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("MatchId");

                    b.HasIndex("SummonerId");

                    b.HasIndex("ChampionId", "TeamPosition");

                    b.HasIndex("MatchId", "SummonerId")
                        .IsUnique();

                    b.ToTable("MatchParticipants");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantItem", b =>
                {
                    b.Property<Guid>("MatchParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MatchParticipantId", "ItemId");

                    b.HasIndex("ItemId", "PatchVersion");

                    b.ToTable("MatchParticipantItems");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantRune", b =>
                {
                    b.Property<Guid>("MatchParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("RuneId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MatchParticipantId", "RuneId");

                    b.HasIndex("RuneId", "PatchVersion");

                    b.ToTable("MatchParticipantRunes");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.ItemVersion", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("ItemId", "PatchVersion");

                    b.HasIndex("PatchVersion");

                    b.ToTable("ItemVersions");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.Patch", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Version");

                    b.ToTable("Patches");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.RuneVersion", b =>
                {
                    b.Property<int>("RuneId")
                        .HasColumnType("integer");

                    b.Property<string>("PatchVersion")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RunePathId")
                        .HasColumnType("integer");

                    b.Property<string>("RunePathName")
                        .HasColumnType("text");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("RuneId", "PatchVersion");

                    b.HasIndex("PatchVersion");

                    b.ToTable("RuneVersions");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentChampionLoadout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CurrentChampionLoadouts");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentDataParameters", b =>
                {
                    b.Property<Guid>("CurrentDataParametersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Patch")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CurrentDataParametersId");

                    b.ToTable("CurrentDataParameters");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.Helpers.UnitWinPercent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CurrentChampionLoadoutId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfGames")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("WinRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CurrentChampionLoadoutId");

                    b.ToTable("UnitWinPercent");
                });

            modelBuilder.Entity("MatchSummoner", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", null)
                        .WithMany()
                        .HasForeignKey("SummonersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.HistoricalRank", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany()
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Rank", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("Ranks")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipant", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.Match", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Account.Summoner", "Summoner")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantItem", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.MatchParticipant", "MatchParticipant")
                        .WithMany("Items")
                        .HasForeignKey("MatchParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Static.ItemVersion", "ItemVersion")
                        .WithMany()
                        .HasForeignKey("ItemId", "PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemVersion");

                    b.Navigation("MatchParticipant");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipantRune", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Match.MatchParticipant", "MatchParticipant")
                        .WithMany("Runes")
                        .HasForeignKey("MatchParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transcendence.Data.Models.LoL.Static.RuneVersion", "RuneVersion")
                        .WithMany()
                        .HasForeignKey("RuneId", "PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchParticipant");

                    b.Navigation("RuneVersion");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.ItemVersion", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Static.Patch", "Patch")
                        .WithMany()
                        .HasForeignKey("PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patch");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Static.RuneVersion", b =>
                {
                    b.HasOne("Transcendence.Data.Models.LoL.Static.Patch", "Patch")
                        .WithMany()
                        .HasForeignKey("PatchVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patch");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.Helpers.UnitWinPercent", b =>
                {
                    b.HasOne("Transcendence.Data.Models.Service.CurrentChampionLoadout", null)
                        .WithMany("UnitWinPercents")
                        .HasForeignKey("CurrentChampionLoadoutId");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Account.Summoner", b =>
                {
                    b.Navigation("MatchParticipants");

                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.Match", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Transcendence.Data.Models.LoL.Match.MatchParticipant", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Runes");
                });

            modelBuilder.Entity("Transcendence.Data.Models.Service.CurrentChampionLoadout", b =>
                {
                    b.Navigation("UnitWinPercents");
                });
#pragma warning restore 612, 618
        }
    }
}
