/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analytics/tierlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    role?: string;
                    rankTier?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TierListResponse"];
                        "application/json": components["schemas"]["TierListResponse"];
                        "text/json": components["schemas"]["TierListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/cache/invalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiKeyListItem"][];
                        "application/json": components["schemas"]["ApiKeyListItem"][];
                        "text/json": components["schemas"]["ApiKeyListItem"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ApiKeyCreateRequest"];
                    "text/json": components["schemas"]["ApiKeyCreateRequest"];
                    "application/*+json": components["schemas"]["ApiKeyCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiKeyCreateResult"];
                        "application/json": components["schemas"]["ApiKeyCreateResult"];
                        "text/json": components["schemas"]["ApiKeyCreateResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/keys/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/keys/{id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiKeyCreateResult"];
                        "application/json": components["schemas"]["ApiKeyCreateResult"];
                        "text/json": components["schemas"]["ApiKeyCreateResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthTokenResponse"];
                        "application/json": components["schemas"]["AuthTokenResponse"];
                        "text/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthTokenResponse"];
                        "application/json": components["schemas"]["AuthTokenResponse"];
                        "text/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                    "text/json": components["schemas"]["RefreshRequest"];
                    "application/*+json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthTokenResponse"];
                        "application/json": components["schemas"]["AuthTokenResponse"];
                        "text/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PasswordResetRequest"];
                    "text/json": components["schemas"]["PasswordResetRequest"];
                    "application/*+json": components["schemas"]["PasswordResetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthMeResponse"];
                        "application/json": components["schemas"]["AuthMeResponse"];
                        "text/json": components["schemas"]["AuthMeResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/champions/{championId}/winrates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    rankTier?: string;
                    region?: string;
                    role?: string;
                };
                header?: never;
                path: {
                    championId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChampionWinRateSummary"];
                        "application/json": components["schemas"]["ChampionWinRateSummary"];
                        "text/json": components["schemas"]["ChampionWinRateSummary"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/champions/{championId}/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    role?: string;
                    rankTier?: string;
                };
                header?: never;
                path: {
                    championId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChampionBuildsResponse"];
                        "application/json": components["schemas"]["ChampionBuildsResponse"];
                        "text/json": components["schemas"]["ChampionBuildsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/champions/{championId}/matchups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    role?: string;
                    rankTier?: string;
                };
                header?: never;
                path: {
                    championId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChampionMatchupsResponse"];
                        "application/json": components["schemas"]["ChampionMatchupsResponse"];
                        "text/json": components["schemas"]["ChampionMatchupsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/champions/cache/invalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summoners/{region}/{gameName}/{tagLine}/live-game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    region: string;
                    gameName: string;
                    tagLine: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LiveGameResponseDto"];
                        "application/json": components["schemas"]["LiveGameResponseDto"];
                        "text/json": components["schemas"]["LiveGameResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summoners/{region}/{name}/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    region: string;
                    name: string;
                    tag: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SummonerProfileResponse"];
                        "application/json": components["schemas"]["SummonerProfileResponse"];
                        "text/json": components["schemas"]["SummonerProfileResponse"];
                    };
                };
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SummonerAcceptedResponse"];
                        "application/json": components["schemas"]["SummonerAcceptedResponse"];
                        "text/json": components["schemas"]["SummonerAcceptedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summoners/{region}/{name}/{tag}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    region: string;
                    name: string;
                    tag: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SummonerAcceptedResponse"];
                        "application/json": components["schemas"]["SummonerAcceptedResponse"];
                        "text/json": components["schemas"]["SummonerAcceptedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summoners/{summonerId}/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    recent?: number;
                };
                header?: never;
                path: {
                    summonerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SummonerOverviewDto"];
                        "application/json": components["schemas"]["SummonerOverviewDto"];
                        "text/json": components["schemas"]["SummonerOverviewDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summoners/{summonerId}/stats/champions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    top?: number;
                };
                header?: never;
                path: {
                    summonerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChampionStatDto"][];
                        "application/json": components["schemas"]["ChampionStatDto"][];
                        "text/json": components["schemas"]["ChampionStatDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summoners/{summonerId}/stats/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    summonerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleStatDto"][];
                        "application/json": components["schemas"]["RoleStatDto"][];
                        "text/json": components["schemas"]["RoleStatDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summoners/{summonerId}/matches/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    summonerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RecentMatchSummaryDtoPagedResultDto"];
                        "application/json": components["schemas"]["RecentMatchSummaryDtoPagedResultDto"];
                        "text/json": components["schemas"]["RecentMatchSummaryDtoPagedResultDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summoners/{summonerId}/matches/{matchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    summonerId: string;
                    matchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MatchDetailDto"];
                        "application/json": components["schemas"]["MatchDetailDto"];
                        "text/json": components["schemas"]["MatchDetailDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FavoriteSummonerDto"][];
                        "application/json": components["schemas"]["FavoriteSummonerDto"][];
                        "text/json": components["schemas"]["FavoriteSummonerDto"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddFavoriteRequest"];
                    "text/json": components["schemas"]["AddFavoriteRequest"];
                    "application/*+json": components["schemas"]["AddFavoriteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FavoriteSummonerDto"];
                        "application/json": components["schemas"]["FavoriteSummonerDto"];
                        "text/json": components["schemas"]["FavoriteSummonerDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/favorites/{favoriteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    favoriteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserPreferencesDto"];
                        "application/json": components["schemas"]["UserPreferencesDto"];
                        "text/json": components["schemas"]["UserPreferencesDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserPreferencesRequest"];
                    "text/json": components["schemas"]["UpdateUserPreferencesRequest"];
                    "application/*+json": components["schemas"]["UpdateUserPreferencesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserPreferencesDto"];
                        "application/json": components["schemas"]["UserPreferencesDto"];
                        "text/json": components["schemas"]["UserPreferencesDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddFavoriteRequest: {
            region?: string | null;
            gameName?: string | null;
            tagLine?: string | null;
        };
        ApiKeyCreateRequest: {
            name?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        ApiKeyCreateResult: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            plaintextKey?: string | null;
            prefix?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        ApiKeyListItem: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            prefix?: string | null;
            isRevoked?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            lastUsedAt?: string | null;
        };
        AuthMeResponse: {
            subject?: string | null;
            name?: string | null;
            roles?: string[] | null;
            authType?: string | null;
        };
        AuthTokenResponse: {
            accessToken?: string | null;
            refreshToken?: string | null;
            /** Format: date-time */
            accessTokenExpiresAtUtc?: string;
            tokenType?: string | null;
        };
        ChampionBuildDto: {
            items?: number[] | null;
            coreItems?: number[] | null;
            situationalItems?: number[] | null;
            /** Format: int32 */
            primaryStyleId?: number;
            /** Format: int32 */
            subStyleId?: number;
            primaryRunes?: number[] | null;
            subRunes?: number[] | null;
            statShards?: number[] | null;
            /** Format: int32 */
            games?: number;
            /** Format: double */
            winRate?: number;
        };
        ChampionBuildsResponse: {
            /** Format: int32 */
            championId?: number;
            role?: string | null;
            rankTier?: string | null;
            patch?: string | null;
            globalCoreItems?: number[] | null;
            builds?: components["schemas"]["ChampionBuildDto"][] | null;
        };
        ChampionMatchupsResponse: {
            /** Format: int32 */
            championId?: number;
            role?: string | null;
            rankTier?: string | null;
            patch?: string | null;
            counters?: components["schemas"]["MatchupEntryDto"][] | null;
            favorableMatchups?: components["schemas"]["MatchupEntryDto"][] | null;
        };
        ChampionStatDto: {
            /** Format: int32 */
            championId?: number;
            /** Format: int32 */
            games?: number;
            /** Format: int32 */
            wins?: number;
            /** Format: int32 */
            losses?: number;
            /** Format: double */
            winRate?: number;
            /** Format: double */
            avgKills?: number;
            /** Format: double */
            avgDeaths?: number;
            /** Format: double */
            avgAssists?: number;
            /** Format: double */
            kdaRatio?: number;
            /** Format: double */
            avgCsPerMin?: number;
            /** Format: double */
            avgVisionScore?: number;
            /** Format: double */
            avgDamageToChamps?: number;
        };
        ChampionWinRateDto: {
            /** Format: int32 */
            championId?: number;
            role?: string | null;
            rankTier?: string | null;
            /** Format: int32 */
            games?: number;
            /** Format: int32 */
            wins?: number;
            /** Format: double */
            winRate?: number;
            /** Format: double */
            pickRate?: number;
            patch?: string | null;
        };
        ChampionWinRateSummary: {
            /** Format: int32 */
            championId?: number;
            patch?: string | null;
            byRoleTier?: components["schemas"]["ChampionWinRateDto"][] | null;
        };
        DataAgeMetadata: {
            /** Format: date-time */
            fetchedAt?: string;
            /** Format: date-span */
            readonly age?: string;
            readonly ageDescription?: string | null;
        };
        FavoriteSummonerDto: {
            /** Format: uuid */
            id?: string;
            summonerPuuid?: string | null;
            platformRegion?: string | null;
            displayName?: string | null;
            /** Format: date-time */
            createdAtUtc?: string;
        };
        LiveGameAnalysisDto: {
            /** Format: date-time */
            generatedAtUtc?: string;
            participants?: components["schemas"]["LiveGameParticipantAnalysisDto"][] | null;
            teams?: components["schemas"]["TeamAnalysisDto"][] | null;
        };
        LiveGameParticipantAnalysisDto: {
            puuid?: string | null;
            /** Format: int32 */
            teamId?: number;
            /** Format: int32 */
            championId?: number;
            rankTier?: string | null;
            rankDivision?: string | null;
            /** Format: int32 */
            leaguePoints?: number | null;
            /** Format: double */
            recentWinRate?: number | null;
            /** Format: double */
            recentKda?: number | null;
            /** Format: double */
            championWinRate?: number | null;
        };
        LiveGameParticipantDto: {
            puuid?: string | null;
            riotId?: string | null;
            summonerId?: string | null;
            /** Format: int32 */
            teamId?: number;
            /** Format: int32 */
            championId?: number;
            /** Format: int32 */
            spell1Id?: number;
            /** Format: int32 */
            spell2Id?: number;
            /** Format: int32 */
            profileIconId?: number;
        };
        LiveGameResponseDto: {
            state?: string | null;
            platformRegion?: string | null;
            gameId?: string | null;
            queueType?: string | null;
            map?: string | null;
            /** Format: date-time */
            gameStartTimeUtc?: string | null;
            /** Format: int64 */
            gameLengthSeconds?: number | null;
            participants?: components["schemas"]["LiveGameParticipantDto"][] | null;
            /** Format: date-time */
            lastUpdatedUtc?: string;
            /** Format: int32 */
            dataAgeSeconds?: number;
            analysis?: components["schemas"]["LiveGameAnalysisDto"];
        };
        LoginRequest: {
            email?: string | null;
            password?: string | null;
        };
        MatchDetailDto: {
            matchId?: string | null;
            /** Format: int64 */
            matchDate?: number;
            /** Format: int32 */
            duration?: number;
            queueType?: string | null;
            patch?: string | null;
            participants?: components["schemas"]["ParticipantDetailDto"][] | null;
        };
        MatchRuneSummaryDto: {
            /** Format: int32 */
            primaryStyleId?: number;
            /** Format: int32 */
            subStyleId?: number;
            /** Format: int32 */
            keystoneId?: number;
        };
        MatchupEntryDto: {
            /** Format: int32 */
            opponentChampionId?: number;
            /** Format: int32 */
            games?: number;
            /** Format: int32 */
            wins?: number;
            /** Format: int32 */
            losses?: number;
            /** Format: double */
            winRate?: number;
        };
        ParticipantDetailDto: {
            puuid?: string | null;
            gameName?: string | null;
            tagLine?: string | null;
            /** Format: int32 */
            teamId?: number;
            /** Format: int32 */
            championId?: number;
            teamPosition?: string | null;
            win?: boolean;
            /** Format: int32 */
            kills?: number;
            /** Format: int32 */
            deaths?: number;
            /** Format: int32 */
            assists?: number;
            /** Format: int32 */
            champLevel?: number;
            /** Format: int32 */
            goldEarned?: number;
            /** Format: int32 */
            totalDamageDealtToChampions?: number;
            /** Format: int32 */
            visionScore?: number;
            /** Format: int32 */
            totalMinionsKilled?: number;
            /** Format: int32 */
            neutralMinionsKilled?: number;
            /** Format: int32 */
            summonerSpell1Id?: number;
            /** Format: int32 */
            summonerSpell2Id?: number;
            items?: number[] | null;
            runes?: components["schemas"]["ParticipantRunesDto"];
        };
        ParticipantRunesDto: {
            /** Format: int32 */
            primaryStyleId?: number;
            /** Format: int32 */
            subStyleId?: number;
            primarySelections?: number[] | null;
            subSelections?: number[] | null;
            statShards?: number[] | null;
        };
        PasswordResetRequest: {
            email?: string | null;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        ProfileChampionStat: {
            /** Format: int32 */
            championId?: number;
            championName?: string | null;
            /** Format: int32 */
            games?: number;
            /** Format: int32 */
            wins?: number;
            /** Format: int32 */
            losses?: number;
            /** Format: double */
            winRate?: number;
            /** Format: double */
            kdaRatio?: number;
        };
        ProfileOverviewStats: {
            /** Format: int32 */
            totalMatches?: number;
            /** Format: int32 */
            wins?: number;
            /** Format: int32 */
            losses?: number;
            /** Format: double */
            winRate?: number;
            /** Format: double */
            avgKills?: number;
            /** Format: double */
            avgDeaths?: number;
            /** Format: double */
            avgAssists?: number;
            /** Format: double */
            kdaRatio?: number;
            /** Format: double */
            avgCsPerMin?: number;
            /** Format: double */
            avgVisionScore?: number;
            /** Format: double */
            avgDamageToChamps?: number;
        };
        ProfileRecentMatch: {
            matchId?: string | null;
            /** Format: int64 */
            matchDate?: number;
            queueType?: string | null;
            win?: boolean;
            /** Format: int32 */
            championId?: number;
            championName?: string | null;
            /** Format: int32 */
            kills?: number;
            /** Format: int32 */
            deaths?: number;
            /** Format: int32 */
            assists?: number;
            /** Format: double */
            csPerMin?: number;
        };
        RankInfo: {
            tier?: string | null;
            division?: string | null;
            /** Format: int32 */
            leaguePoints?: number;
            /** Format: int32 */
            wins?: number;
            /** Format: int32 */
            losses?: number;
        };
        RecentMatchSummaryDto: {
            matchId?: string | null;
            /** Format: int64 */
            matchDate?: number;
            /** Format: int32 */
            durationSeconds?: number;
            queueType?: string | null;
            win?: boolean;
            /** Format: int32 */
            championId?: number;
            teamPosition?: string | null;
            /** Format: int32 */
            kills?: number;
            /** Format: int32 */
            deaths?: number;
            /** Format: int32 */
            assists?: number;
            /** Format: int32 */
            visionScore?: number;
            /** Format: int32 */
            damageToChamps?: number;
            /** Format: double */
            csPerMin?: number;
            /** Format: int32 */
            summonerSpell1Id?: number;
            /** Format: int32 */
            summonerSpell2Id?: number;
            items?: number[] | null;
            runes?: components["schemas"]["MatchRuneSummaryDto"];
        };
        RecentMatchSummaryDtoPagedResultDto: {
            items?: components["schemas"]["RecentMatchSummaryDto"][] | null;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        RecentPerformanceDto: {
            matchId?: string | null;
            win?: boolean;
            /** Format: int32 */
            kills?: number;
            /** Format: int32 */
            deaths?: number;
            /** Format: int32 */
            assists?: number;
            /** Format: double */
            csPerMin?: number;
            /** Format: int32 */
            visionScore?: number;
            /** Format: int32 */
            damageToChamps?: number;
        };
        RefreshRequest: {
            refreshToken?: string | null;
        };
        RegisterRequest: {
            email?: string | null;
            password?: string | null;
        };
        RoleStatDto: {
            role?: string | null;
            /** Format: int32 */
            games?: number;
            /** Format: int32 */
            wins?: number;
            /** Format: int32 */
            losses?: number;
            /** Format: double */
            winRate?: number;
        };
        SummonerAcceptedResponse: {
            message?: string | null;
            poll?: string | null;
            /** Format: int32 */
            retryAfterSeconds?: number | null;
        };
        SummonerOverviewDto: {
            /** Format: uuid */
            summonerId?: string;
            /** Format: int32 */
            totalMatches?: number;
            /** Format: int32 */
            wins?: number;
            /** Format: int32 */
            losses?: number;
            /** Format: double */
            winRate?: number;
            /** Format: double */
            avgKills?: number;
            /** Format: double */
            avgDeaths?: number;
            /** Format: double */
            avgAssists?: number;
            /** Format: double */
            kdaRatio?: number;
            /** Format: double */
            avgCsPerMin?: number;
            /** Format: double */
            avgVisionScore?: number;
            /** Format: double */
            avgDamageToChamps?: number;
            /** Format: double */
            avgGameDurationMin?: number;
            recentPerformance?: components["schemas"]["RecentPerformanceDto"][] | null;
        };
        SummonerProfileResponse: {
            /** Format: uuid */
            summonerId?: string;
            puuid?: string | null;
            gameName?: string | null;
            tagLine?: string | null;
            /** Format: int32 */
            summonerLevel?: number;
            /** Format: int32 */
            profileIconId?: number;
            soloRank?: components["schemas"]["RankInfo"];
            flexRank?: components["schemas"]["RankInfo"];
            overviewStats?: components["schemas"]["ProfileOverviewStats"];
            topChampions?: components["schemas"]["ProfileChampionStat"][] | null;
            recentMatches?: components["schemas"]["ProfileRecentMatch"][] | null;
            profileAge?: components["schemas"]["DataAgeMetadata"];
            rankAge?: components["schemas"]["DataAgeMetadata"];
            statsAge?: components["schemas"]["DataAgeMetadata"];
        };
        TeamAnalysisDto: {
            /** Format: int32 */
            teamId?: number;
            /** Format: double */
            averageRecentWinRate?: number;
            /** Format: double */
            averageChampionWinRate?: number;
            /** Format: double */
            averageRankScore?: number;
            /** Format: double */
            compositeScore?: number;
            /** Format: double */
            estimatedWinProbability?: number;
            strengths?: string[] | null;
            weaknesses?: string[] | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        TierGrade: 0 | 1 | 2 | 3 | 4;
        TierListEntry: {
            /** Format: int32 */
            championId?: number;
            role?: string | null;
            tier?: components["schemas"]["TierGrade"];
            /** Format: double */
            compositeScore?: number;
            /** Format: double */
            winRate?: number;
            /** Format: double */
            pickRate?: number;
            /** Format: int32 */
            games?: number;
            movement?: components["schemas"]["TierMovement"];
            previousTier?: components["schemas"]["TierGrade"];
        };
        TierListResponse: {
            patch?: string | null;
            role?: string | null;
            rankTier?: string | null;
            entries?: components["schemas"]["TierListEntry"][] | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        TierMovement: 0 | 1 | 2 | 3;
        UpdateUserPreferencesRequest: {
            preferredRegion?: string | null;
            preferredRankTier?: string | null;
            livePollingEnabled?: boolean;
        };
        UserPreferencesDto: {
            preferredRegion?: string | null;
            preferredRankTier?: string | null;
            livePollingEnabled?: boolean;
            /** Format: date-time */
            updatedAtUtc?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
